### ISSUE TITLE
Support for a different base branch?

### ISSUE THREAD

**Issue by bunnymatic** [hovancik/middleman-github-deploy#11]
Does your plugin/service support a base branch that is not `master`?  We've been moving repos to use `main` as the primary branch and when I try to deploy with `mgd` on one of those repos, it doesn't seem to work out.

If you don't already have that support, I might look into it and submit a PR.

Thanks

**Comment by hovancik** [comment]
Hi, you can do `mgd --branch=main`. Does that solve your issue?

**Comment by bunnymatic** [comment]
Yes.  Well that was dumb.  I saw that option in the docs and somehow walked right past it.

Thanks.
